export function renderPanelRecoveryHtml(message = "面板脚本启动失败或响应超时。", diagnostic = "{}"): string {
  const nonce = String(Date.now());
  const entities: Record<string, string> = { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" };
  const escaped = String(message).replace(/[&<>"']/g, (ch) => entities[ch] || ch);
  const diagnosticText = String(diagnostic || "{}").slice(0, 16 * 1024).replace(/[&<>"']/g, (ch) => entities[ch] || ch);
  return `<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'nonce-${nonce}';"><style>body{font-family:var(--vscode-font-family);color:var(--vscode-editor-foreground);padding:18px;line-height:1.5}button{color:var(--vscode-button-foreground);background:var(--vscode-button-background);border:0;border-radius:4px;padding:7px 12px;margin-right:8px;cursor:pointer}pre{max-height:240px;overflow:auto;white-space:pre-wrap;font-size:11px}</style></head><body><h3>SimpleExperiment 面板暂时不可用</h3><p>${escaped}</p><details><summary>本次诊断摘要</summary><pre>${diagnosticText}</pre></details><button id="reload" type="button">重新加载面板</button><button id="low-effects" type="button">低效果模式重载</button><button id="reload-window" type="button">重载窗口</button><button id="copy" type="button">复制诊断摘要</button><script nonce="${nonce}">const vscode=acquireVsCodeApi();document.getElementById("reload").addEventListener("click",()=>vscode.postMessage({command:"reloadPanel"}));document.getElementById("low-effects").addEventListener("click",()=>vscode.postMessage({command:"reloadPanelLowEffects"}));document.getElementById("reload-window").addEventListener("click",()=>vscode.postMessage({command:"reloadWindow"}));document.getElementById("copy").addEventListener("click",()=>vscode.postMessage({command:"copyPanelDiagnostics"}));</script></body></html>`;
}

export function renderPanelReloadRequiredHtml(versions: { runningVersion?: string; installedVersion?: string; registryState?: string; reason?: string; runningFingerprint?: string; diskFingerprint?: string }): string {
  const nonce = String(Date.now());
  const escape = (value: unknown) => String(value || "未知").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[character] || character));
  const contentMismatch = versions.registryState === "content_mismatch" || versions.reason === "content_mismatch";
  const explanation = contentMismatch ? `版本号均为 ${escape(versions.runningVersion)}，但当前运行构建与磁盘构建不一致。` : `正在运行：<code>${escape(versions.runningVersion)}</code><br>已安装：<code>${escape(versions.installedVersion)}</code>`;
  const fingerprints = `<small>构建指纹：${escape(String(versions.runningFingerprint || "").slice(0, 12) || "未知")} / ${escape(String(versions.diskFingerprint || "").slice(0, 12) || "未知")}</small>`;
  return `<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'nonce-${nonce}';"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:var(--vscode-font-family);color:var(--vscode-editor-foreground);padding:20px;line-height:1.6}button{color:var(--vscode-button-foreground);background:var(--vscode-button-background);border:0;border-radius:4px;padding:8px 14px;cursor:pointer}code{font-family:var(--vscode-editor-font-family)}</style></head><body><h2>SimpleExperiment 需要重载</h2><p>${explanation}</p>${fingerprints}<p>需要重载 VS Code 窗口才能切换到一致构建。当前项目和运行中的远端任务不会因此重新提交。</p><button id="reload-window" type="button">重载窗口</button><script nonce="${nonce}">const vscode=acquireVsCodeApi();document.getElementById("reload-window").addEventListener("click",()=>vscode.postMessage({command:"reloadWindow"}));</script></body></html>`;
}

export function renderPanelMaintenanceHtml(message = "正在安装更新，完成后将重载窗口。"): string {
  const escaped = String(message).replace(/[&<>"']/g, (ch) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[ch] || ch));
  return `<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline';"><style>body{font-family:var(--vscode-font-family);color:var(--vscode-editor-foreground);padding:24px}</style></head><body><h3>正在安装更新</h3><p>${escaped}</p></body></html>`;
}
