export const scalarViewerHtml = String.raw`<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SimpleExperiment 曲线</title>
<style>
:root{font-family:system-ui,"Microsoft YaHei",sans-serif;color:#172033;background:#f3f6fa}*{box-sizing:border-box}[hidden]{display:none!important}body{margin:0}
header{display:flex;align-items:center;gap:12px;padding:12px 18px;background:#fff;border-bottom:1px solid #dce3ed}header h1{font-size:17px;margin:0 16px 0 0}button,input,select{font:inherit}button{border:1px solid #ccd6e4;background:#fff;border-radius:6px;padding:6px 10px;cursor:pointer}button:hover{background:#eef3fa}button.active{background:#4d68e8;color:#fff;border-color:#4d68e8}.spacer{flex:1}.status{font-size:12px;color:#65748a}main{display:grid;grid-template-columns:minmax(240px,310px) minmax(0,1fr);height:calc(100vh - 58px)}aside{overflow:auto;background:#fff;border-right:1px solid #dce3ed;padding:12px}.content{overflow:auto;padding:14px}.tree details{margin:4px 0 4px 11px}.tree summary{cursor:pointer;padding:5px;border-radius:5px;overflow-wrap:anywhere}.tree summary:hover{background:#f1f5fb}.tree .case{display:flex;align-items:center;gap:4px}.tree .tag{display:block;width:calc(100% - 20px);margin:3px 0 3px 20px;text-align:left}.muted{color:#65748a;font-size:12px}.pill{padding:2px 7px;border-radius:12px;background:#e9edf4;font-size:11px}.chart{background:#fff;border:1px solid #dce3ed;border-radius:8px;padding:12px}.chart canvas{display:block;width:100%;height:460px}.controls{display:flex;flex-wrap:wrap;gap:10px;align-items:center;margin-bottom:9px}.tooltip{min-height:25px;white-space:pre-wrap;font-size:12px;color:#334155}.error{color:#bd2929}.native{width:100%;height:calc(100vh - 94px);border:1px solid #dce3ed;background:#fff}#settings{display:none;position:absolute;right:15px;top:55px;background:#fff;border:1px solid #ccd6e4;box-shadow:0 8px 25px #182a4524;padding:15px;border-radius:8px;z-index:3}#settings.open{display:block}@media(max-width:760px){main{grid-template-columns:1fr}aside{max-height:34vh;border-right:0;border-bottom:1px solid #dce3ed}.content{height:calc(66vh - 58px)}}
</style></head><body>
<header><h1>实验曲线</h1><button id="scalarTab" class="active">标量</button><button id="nativeTab">图像 · 直方图 · 网络图</button><span class="spacer"></span><span id="status" class="status"></span><button id="refresh" title="手动刷新">⟳ 刷新</button><button id="settingsButton" title="刷新设置">⚙ 设置</button></header>
<div id="settings"><label><input id="autoRefresh" type="checkbox" checked> 自动刷新</label><p><label>间隔 <input id="interval" type="number" min="1" step="1" value="5" style="width:70px"> 秒</label></p><p class="muted">最短 1 秒；请求受插件预算约束，繁忙时自动退避。</p><label><input id="band" type="checkbox"> 均值 ± 样本标准差</label><p><label><input id="raw" type="checkbox"> 显示当前实验的 seed 明细</label></p></div>
<main id="scalarPage"><aside><div class="muted">Plan → 实验 → 指标。勾选实验以对比均值；仅展开项读取数据。</div><div id="tree" class="tree"></div></aside><div class="content"><div id="heading" class="muted">展开实验并选择指标。</div><div id="chart" class="chart" hidden><div id="legend" class="controls"></div><canvas id="plot"></canvas><div id="tooltip" class="tooltip"></div></div></div></main>
<div id="nativePage" hidden><iframe id="nativeFrame" class="native" title="TensorBoard 其他内容"></iframe></div>
<script>
(function(){
  var server=__SCALAR_VIEWER_SERVER__;
  var tree=document.getElementById('tree'),status=document.getElementById('status'),canvas=document.getElementById('plot');
  var selected=new Map(),active=null,catalog=null,charts=[],backoff=0,nativeStarted=false,seriesGeneration=0,readControllers=new Map(),autoRefreshTimer=0;
  var palette=['#3766df','#d97706','#0a9b71','#bb3ba8','#d23d48','#6355c8','#087eaa','#a06328','#5b8f25','#e56b9f','#137c6b','#b05b16','#7b4fc4','#ba7f12','#d8508b','#4c879e','#8f581c','#4f8b60','#bc6f64','#5762a0'];
  var interval=document.getElementById('interval'),auto=document.getElementById('autoRefresh'),band=document.getElementById('band'),raw=document.getElementById('raw');
  function storageGet(name,fallback){try{return localStorage.getItem(name)||fallback}catch(_){return fallback}}function storageSet(name,value){try{localStorage.setItem(name,value)}catch(_){}}
  interval.value=String(Math.max(1,Number(storageGet('scalarInterval',5))));auto.checked=storageGet('scalarAuto','true')!=='false';
  band.checked=storageGet('scalarBand','false')==='true';raw.checked=storageGet('scalarRaw','false')==='true';
  function key(plan,experiment){return plan+'|'+experiment}
  function make(tag,cls,label){var el=document.createElement(tag);if(cls)el.className=cls;if(label!==undefined)el.textContent=label;return el}
  function message(text,error){status.textContent=text;status.className=error?'status error':'status'}
  function readScope(action,extra){return action==='tags'?'tags:'+key(extra&&extra.planFile||'',extra&&extra.case||''):action}
  function cancelRead(scope){var controller=readControllers.get(scope);if(controller){readControllers.delete(scope);controller.abort()}}
  function cancelScalarReads(){Array.from(readControllers.keys()).forEach(function(scope){cancelRead(scope)})}
  function cancelPlanTagReads(planFile){var prefix='tags:'+planFile+'|';Array.from(readControllers.keys()).forEach(function(scope){if(scope.indexOf(prefix)===0)cancelRead(scope)})}
  async function call(action,extra){var scope=action==='native.open'?'':readScope(action,extra),controller=null;if(scope){if(scope==='series'||scope==='catalog')cancelRead(scope);controller=new AbortController();readControllers.set(scope,controller);if(scope.indexOf('tags:')===0){var tags=Array.from(readControllers.keys()).filter(function(name){return name.indexOf('tags:')===0});while(tags.length>24){cancelRead(tags.shift())}}}try{var result=await fetch('/tensorboard/api?server='+encodeURIComponent(server),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.assign({action:action},extra||{})),signal:controller&&controller.signal});var data=await result.json();if(!result.ok||data.error){var failure=new Error(data.error||'HTTP '+result.status);failure.retryAfterMs=data.retryAfterMs||1000;throw failure}return data}finally{if(scope&&readControllers.get(scope)===controller)readControllers.delete(scope)}}
  function mergeCatalog(data){var map=new Map();(data.plans||[]).forEach(function(plan){var found=map.get(plan.planFile);if(!found){found={planFile:plan.planFile,suite:plan.suite,cases:new Map()};map.set(plan.planFile,found)}(plan.cases||[]).forEach(function(item){var prior=found.cases.get(item.case);if(!prior){prior={case:item.case,expectedSeeds:item.expectedSeeds||0};found.cases.set(item.case,prior)}prior.expectedSeeds=Math.max(prior.expectedSeeds,item.expectedSeeds||0)})});return Array.from(map.values())}
  function renderCatalog(data){catalog=mergeCatalog(data);tree.replaceChildren();catalog.forEach(function(plan){var p=make('details'),ps=make('summary','',plan.suite+' · '+(plan.planFile==='__unassigned__'?'未归属':plan.planFile));p.appendChild(ps);tree.appendChild(p);p.addEventListener('toggle',function(){if(!p.open)cancelPlanTagReads(plan.planFile);if(!p.open&&active&&active.planFile===plan.planFile){active=null;cancelRead('series');seriesGeneration++;clearAutoRefresh();document.getElementById('chart').hidden=true}});Array.from(plan.cases.values()).forEach(function(item){var c=make('details'),head=make('summary','case'),check=make('input');check.type='checkbox';check.title='加入对比';check.addEventListener('click',function(e){e.stopPropagation()});check.addEventListener('change',function(){var id=key(plan.planFile,item.case);if(check.checked){if(selected.size>=20){check.checked=false;message('最多同时比较 20 个实验',true);return}selected.set(id,{planFile:plan.planFile,case:item.case})}else selected.delete(id);if(active)void refreshSeries()});head.appendChild(check);head.appendChild(make('span','',item.case+' · '+(item.expectedSeeds?item.expectedSeeds+' seeds':'历史日志')));c.appendChild(head);p.appendChild(c);c.addEventListener('toggle',async function(){if(!c.open){cancelRead('tags:'+key(plan.planFile,item.case));if(active&&active.planFile===plan.planFile&&active.case===item.case){active=null;cancelRead('series');seriesGeneration++;clearAutoRefresh();document.getElementById('chart').hidden=true}return}if(c.dataset.loaded)return;c.dataset.loaded='1';c.appendChild(make('div','muted','读取指标…'));try{var result=await call('tags',{planFile:plan.planFile,case:item.case});if(!c.open){c.dataset.loaded='';return}c.lastChild.remove();(result.tags||[]).forEach(function(tag){var button=make('button','tag',tag);button.addEventListener('click',function(){active={planFile:plan.planFile,case:item.case,tag:tag};if(!selected.size){selected.set(key(plan.planFile,item.case),{planFile:plan.planFile,case:item.case});check.checked=true}void refreshSeries()});c.appendChild(button)});if(result.unsupportedFiles&&result.unsupportedFiles.length)c.appendChild(make('div','error','存在不支持的 event 记录：'+result.unsupportedFiles.join(', ')));if(!(result.tags||[]).length)c.appendChild(make('div','muted','暂无标量指标'))}catch(e){if(e.name==='AbortError'){if(c.lastChild&&c.lastChild.className==='muted'&&c.lastChild.textContent==='读取指标…')c.lastChild.remove();c.dataset.loaded='';return}c.lastChild.textContent=String(e.message);c.dataset.loaded=''}})})})}
  async function loadCatalog(){try{var result=await call('catalog');if(document.hidden||document.getElementById('scalarPage').hidden)return;renderCatalog(result);message('目录已更新'+(result.offlineServers&&result.offlineServers.length?' · 离线 '+result.offlineServers.join(', '):''))}catch(e){if(e.name!=='AbortError')message('目录读取失败：'+e.message,true)}}
  async function refreshSeries(){if(!active||document.hidden||document.getElementById('scalarPage').hidden)return;var generation=++seriesGeneration;var requestActive=active,groups=Array.from(selected.values());if(!groups.some(function(x){return key(x.planFile,x.case)===key(requestActive.planFile,requestActive.case)})){if(groups.length>=20){message('最多同时比较 20 个实验，请先移除一个已选实验',true);scheduleAutoRefresh();return}groups.unshift({planFile:requestActive.planFile,case:requestActive.case})}try{var result=await call('series',{groups:groups,tag:requestActive.tag});if(generation!==seriesGeneration||!active||key(active.planFile,active.case)!==key(requestActive.planFile,requestActive.case)||active.tag!==requestActive.tag)return;charts=result.charts||[];document.getElementById('chart').hidden=false;document.getElementById('heading').textContent=requestActive.tag+' · '+charts.length+' 条均值线';var legend=document.getElementById('legend');legend.replaceChildren();charts.forEach(function(row,i){var pill=make('span','pill',row.case+' · '+(row.rawOnly?'原始曲线 '+row.seeds.length+' 条':row.points.length+' 点 · '+(row.points.length?row.points[row.points.length-1].n:0)+'/'+(row.expectedSeeds||'?')));pill.style.borderLeft='4px solid '+palette[i%palette.length];legend.appendChild(pill)});if(result.unsupportedFiles&&result.unsupportedFiles.length)legend.appendChild(make('span','error','不支持的 event 格式：'+result.unsupportedFiles.join(', ')));draw();backoff=0;message('更新于 '+new Date().toLocaleTimeString()+(result.offlineServers&&result.offlineServers.length?' · 离线 '+result.offlineServers.join(', '):''))}catch(e){if(e.name==='AbortError')return;if(generation===seriesGeneration){backoff=Math.min(60000,Math.max(1000,backoff?backoff*2:Number(e.retryAfterMs)||1000));message('刷新延后 '+Math.ceil(backoff/1000)+' 秒：'+e.message,true)}}finally{if(generation===seriesGeneration){scheduleAutoRefresh()}}}
  function clearAutoRefresh(){if(autoRefreshTimer){clearTimeout(autoRefreshTimer);autoRefreshTimer=0}}
  function scheduleAutoRefresh(delay){clearAutoRefresh();if(document.hidden||document.getElementById('scalarPage').hidden||!auto.checked||!active)return;var wait=delay===undefined?Math.max(1000,Number(interval.value)*1000,backoff):Math.max(0,Number(delay)||0);autoRefreshTimer=setTimeout(function(){autoRefreshTimer=0;void refreshSeries()},wait)}
  function bounds(){var all=charts.flatMap(function(c){return c.rawOnly?(c.seeds||[]).flatMap(function(s){return(s.points||[]).map(function(p){return{step:p[0],mean:p[1],std:null}})}):c.points||[]});if(!all.length)return null;var xs=all.map(function(p){return p.step}),ys=all.flatMap(function(p){return band.checked&&p.std!==null?[p.mean-p.std,p.mean+p.std]:[p.mean]});var x0=Math.min.apply(null,xs),x1=Math.max.apply(null,xs),y0=Math.min.apply(null,ys),y1=Math.max.apply(null,ys);if(x0===x1)x1=x0+1;if(y0===y1){y0-=1;y1+=1}return{x0:x0,x1:x1,y0:y0,y1:y1}}
  function draw(){var rect=canvas.getBoundingClientRect(),ratio=devicePixelRatio||1,w=Math.max(300,rect.width),h=Math.max(220,rect.height);canvas.width=Math.round(w*ratio);canvas.height=Math.round(h*ratio);var ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);ctx.clearRect(0,0,w,h);var b=bounds();if(!b){ctx.fillStyle='#64748b';ctx.fillText('暂无曲线数据',30,40);return}var left=56,right=w-20,top=20,bottom=h-38,X=function(v){return left+(v-b.x0)/(b.x1-b.x0)*(right-left)},Y=function(v){return bottom-(v-b.y0)/(b.y1-b.y0)*(bottom-top)};ctx.strokeStyle='#dbe2eb';ctx.fillStyle='#64748b';ctx.font='12px system-ui';for(var k=0;k<=4;k++){var y=top+(bottom-top)*k/4;ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke();ctx.fillText((b.y1-(b.y1-b.y0)*k/4).toPrecision(3),5,y+4)}ctx.fillText(String(b.x0),left,bottom+23);ctx.fillText(String(b.x1),right-30,bottom+23);charts.forEach(function(c,i){var points=c.points||[],color=palette[i%palette.length];if(band.checked&&points.length){ctx.fillStyle=color+'30';ctx.beginPath();points.forEach(function(p,j){if(j===0)ctx.moveTo(X(p.step),Y(p.mean+(p.std||0)));else ctx.lineTo(X(p.step),Y(p.mean+(p.std||0)))});points.slice().reverse().forEach(function(p){ctx.lineTo(X(p.step),Y(p.mean-(p.std||0)))});ctx.closePath();ctx.fill()}ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();points.forEach(function(p,j){if(j===0)ctx.moveTo(X(p.step),Y(p.mean));else ctx.lineTo(X(p.step),Y(p.mean))});ctx.stroke();if((raw.checked||c.rawOnly)&&key(c.planFile,c.case)===key(active.planFile,active.case))(c.seeds||[]).forEach(function(seed){ctx.strokeStyle=color+'55';ctx.lineWidth=1;ctx.beginPath();(seed.points||[]).forEach(function(p,j){if(j===0)ctx.moveTo(X(p[0]),Y(p[1]));else ctx.lineTo(X(p[0]),Y(p[1]))});ctx.stroke()})});canvas._chart={bounds:b,left:left,right:right}}
  canvas.addEventListener('mousemove',function(e){var view=canvas._chart;if(!view)return;var x=e.offsetX,b=view.bounds,step=b.x0+(x-view.left)/(view.right-view.left)*(b.x1-b.x0),lines=[];charts.forEach(function(c){if(c.rawOnly){(c.seeds||[]).forEach(function(seed){var nearest=(seed.points||[]).reduce(function(best,p){return !best||Math.abs(p[0]-step)<Math.abs(best[0]-step)?p:best},null);if(nearest)lines.push(c.case+' · '+seed.seed+' · step '+nearest[0]+' · 值 '+Number(nearest[1]).toPrecision(5))});return}var nearest=(c.points||[]).reduce(function(best,p){return !best||Math.abs(p.step-step)<Math.abs(best.step-step)?p:best},null);if(nearest)lines.push(c.case+' · step '+nearest.step+' · 均值 '+nearest.mean.toPrecision(5)+' · SD '+(nearest.std===null?'—':nearest.std.toPrecision(4))+' · n '+nearest.n+'/'+(c.expectedSeeds||'?')+' · '+Object.entries(nearest.seeds).map(function(x){return x[0]+':'+Number(x[1]).toPrecision(4)}).join('，'))});document.getElementById('tooltip').textContent=lines.join('\n')});
  document.getElementById('refresh').onclick=function(){if(active)void refreshSeries();else void loadCatalog()};document.getElementById('settingsButton').onclick=function(){document.getElementById('settings').classList.toggle('open')};
  interval.onchange=function(){interval.value=String(Math.max(1,Math.floor(Number(interval.value)||5)));storageSet('scalarInterval',interval.value);scheduleAutoRefresh(Number(interval.value)*1000)};auto.onchange=function(){storageSet('scalarAuto',String(auto.checked));scheduleAutoRefresh(auto.checked?0:undefined)};band.onchange=function(){storageSet('scalarBand',String(band.checked));draw()};raw.onchange=function(){storageSet('scalarRaw',String(raw.checked));draw()};window.addEventListener('resize',draw);
  document.getElementById('scalarTab').onclick=function(){document.getElementById('scalarPage').hidden=false;document.getElementById('nativePage').hidden=true;this.classList.add('active');document.getElementById('nativeTab').classList.remove('active');if(!catalog)void loadCatalog();else scheduleAutoRefresh(0)};
  document.getElementById('nativeTab').onclick=async function(){clearAutoRefresh();cancelScalarReads();seriesGeneration++;this.classList.add('active');document.getElementById('scalarTab').classList.remove('active');document.getElementById('scalarPage').hidden=true;document.getElementById('nativePage').hidden=false;if(nativeStarted)return;try{message('启动原生 TensorBoard 内容…');await call('native.open');document.getElementById('nativeFrame').src='/api/tensorboard/ui/?server='+encodeURIComponent(server);nativeStarted=true;message('原生内容已嵌入')}catch(e){message('原生内容启动失败：'+e.message,true)}};
  document.addEventListener('visibilitychange',function(){if(document.hidden){clearAutoRefresh();seriesGeneration++;cancelScalarReads();return}if(document.getElementById('scalarPage').hidden)return;if(!catalog)void loadCatalog();else if(active)void refreshSeries();else scheduleAutoRefresh()});
  window.addEventListener('pagehide',function(){clearAutoRefresh();seriesGeneration++;cancelScalarReads()});
  void loadCatalog();
})();
</script></body></html>`;
